version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor: python/default  
    steps:
      - checkout  

      
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q  # Runs tests with a limit of 1 failure

workflows:
  build_test_deploy:
    jobs:
      - build_and_test  
