version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test-weather-app:
    docker:
      - image: circleci/python:3.9  
    steps:
      - checkout  
      - python/install-packages:
          pkg-manager: pip
          packages:  
            - flask
            - requests
            - python-dotenv
      - run:
          name: Set Environment Variables
          command: |
            echo "API_KEY=7358abfeb3f3b0992112331542b8b769" > .env  # Set API key in .env file
      - run:
          name: Test Weather App
          command: |
            python <<EOF
from weather_app import main
result = main('Toronto', 'CA')
print(f'Current temperature: {result.temperature}°C')
print(f'Weather conditions: {result.main} - {result.description}')
EOF

workflows:
  test-weather-app-workflow:
    jobs:
      - build-and-test-weather-app
