version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test-weather-app:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # checkout your repository
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Set up the environment
          command: |
            echo "Setting up environment..."
            pip install -r web_apps/requirements.txt  # or any necessary packages
      - run:
          name: Run weather app test
          command: |
            python -c "from weather_app import main; result = main('Toronto', 'CA'); print(f'Current temperature: {result.temperature}°C'); print(f'Weather conditions: {result.main} - {result.description}')"
          
workflows:
  version: 2
  test-weather-app-workflow:
    jobs:
      - build-and-test-weather-app
